namespace twiggySprites {
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy01 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy02 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy03 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy04 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy05 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy06 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy07 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy08 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy09 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const twiggy27 = image.ofBuffer(hex``);

}
